version: '3.8'

services:
  magnus-gem:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      - BUNDLE_PATH=/app/vendor/bundle
    command: bash