services:
  magnus-gem:
    build:
      context: .
      args:
        TARGET_ARCH: ${TARGET_ARCH:-x86_64-linux}
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    environment:
      - BUNDLE_PATH=/app/vendor/bundle
    command: bash