name: Cross-compile Native Gem

on:
  workflow_dispatch:
    inputs:
      create_pr:
        description: 'Create PR with compiled gems'
        required: true
        default: false
        type: boolean

jobs:
  cross-compile:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-linux
            ruby: "2.7"
          - os: ubuntu-latest
            target: aarch64-linux
            ruby: "2.7"
        
    runs-on: ${{ matrix.platform.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.platform.ruby }}
        bundler-cache: true
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.85.0
    
    - name: Install cross-compilation tools
      if: matrix.platform.target == 'aarch64-linux'
      run: |
        sudo apt-get install -y gcc-aarch64-linux-gnu
        rustup target add aarch64-unknown-linux-gnu
    
    - name: Cross-compile gem
      run: |
        if [ "${{ matrix.platform.target }}" = "aarch64-linux" ]; then
          export CARGO_BUILD_TARGET=aarch64-unknown-linux-gnu
          export CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          export RB_SYS_CARGO_TARGET=aarch64-unknown-linux-gnu
          bundle exec rake compile
        else
          bundle exec rake compile
        fi
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: so-${{ matrix.platform.target }}
        path: lib/magnus_multi_build/*.so
        retention-days: 30

  create-pr:
    needs: cross-compile
    runs-on: ubuntu-latest
    if: github.event.inputs.create_pr == 'true'
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: compiled-gems
    
    - name: Create release branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        branch_name="compiled-binaries-$(date +%Y%m%d-%H%M%S)"
        git checkout -b $branch_name
        
        # Copy compiled .so files to architecture-specific directories
        mkdir -p lib/magnus_multi_build/x86_64-linux
        mkdir -p lib/magnus_multi_build/aarch64-linux
        
        # Copy x86_64 binaries
        find compiled-gems/so-x86_64-linux -name "*.so" -exec cp {} lib/magnus_multi_build/x86_64-linux/ \; 2>/dev/null || true
        
        # Copy aarch64 binaries  
        find compiled-gems/so-aarch64-linux -name "*.so" -exec cp {} lib/magnus_multi_build/aarch64-linux/ \; 2>/dev/null || true
        
        # Add binaries to git
        git add lib/magnus_multi_build/
        git commit -m "Add pre-compiled native binaries for multiple architectures

        - x86_64-linux
        - aarch64-linux
        
        Built from commit: ${{ github.sha }}"
        
        git push origin $branch_name
        echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.BRANCH_NAME }}
        title: "Add pre-compiled gems for multi-architecture support"
        body: |
          ## Summary
          This PR adds pre-compiled native gems for multiple architectures:
          
          - ✅ x86_64-linux (Intel/AMD 64-bit)
          - ✅ aarch64-linux (ARM 64-bit)
          
          ## Testing
          - [ ] Test x86_64-linux gem in Docker container
          - [ ] Test aarch64-linux gem in ARM Docker container
          
          ## Files Added
          - `release/gems/` - Contains pre-compiled gem files
          
          Built from commit: ${{ github.sha }}
        draft: false