name: Test Cross-Compiled Binaries

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    paths:
      - 'lib/magnus_multi_build/**/*.so'

jobs:
  test-x86_64:
    runs-on: ubuntu-22.04  # Intel/AMD x86_64
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.8'

    - name: Install dependencies
      run: bundle install
        
    - name: Test x86_64-linux binary
      env:
        MAGNUS_TARGET_ARCH: x86_64-linux
      run: |
        bundle exec ruby -r "./lib/magnus_multi_build" -e "
         puts \"#{RustStringUtils.reverse('hello')} - #{RustStringUtils.duckdb_query('42')}\"
        " > output.txt

    - name: Verify x86_64 output
      run: |
        expected="olleh - 42"
        actual=$(cat output.txt)
        if [ "$actual" != "$expected" ]; then
          echo "Expected: $expected"
          echo "Actual: $actual"
          exit 1
        fi
        echo "Test passed: $actual"

  test-aarch64:
    runs-on: ubuntu-22.04-arm  # ARM aarch64
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.8'

    - name: Install dependencies
      run: bundle install
        
    - name: Test aarch64-linux binary
      env:
        MAGNUS_TARGET_ARCH: aarch64-linux
      run: |
        bundle exec ruby -r "./lib/magnus_multi_build" -e "
          puts \"#{RustStringUtils.reverse('hello')} - #{RustStringUtils.duckdb_query('42')}\"
        " > output.txt

    - name: Verify aarch64 output
      run: |
        expected="olleh - 42"
        actual=$(cat output.txt)
        if [ "$actual" != "$expected" ]; then
          echo "Expected: $expected"
          echo "Actual: $actual"
          exit 1
        fi
        echo "Test passed: $actual"